<main class="d-flex flex-column">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb m-0">
        <li class="breadcrumb-item">Administration</li>
        <li class="breadcrumb-item active" aria-current="page">Gestion des articles</li>
    </ol>
  </nav>
  <div class="flex-grow-1 d-md-flex align-items-stretch">   
    <?php include 'admin_menu.phtml'; ?>
    <section class="col-md-7 py-4 mx-auto">
      <header class="jumbotron text-center">
        <h2 class="text-center mb-4 display-4">Gestion des articles</h2>
        <p class="lead">Liste des articles</p>
        <hr class="my-4">
      </header>
      <nav class="mb-4">
        <a class="btn bg text-white" href="admin_posts_new.php">
          <i class="fas fa-plus" aria-hidden="true"></i>
          Créer un article
        </a>
      </nav>
      <table class="table table-striped">
        <caption>
          Liste des posts classés par ordre chronologique inversé
          <strong>
              (<?= $countPosts ?> articles au total)
            </strong>
        </caption>
        <thead class="thead-dark">
          <tr>
            <th>ID</th>
            <th>Création</th>
            <th>Titre</th>
            <th>Auteur</th>
            <th>Catégorie</th>
            <th>Modifier</th>
            <th>Supprimer</th>
          </tr>
        </thead>
        <tbody>
          <?php foreach($posts as $post): ?>
          <tr>
            <td>
              <?= htmlspecialchars( $post['Id'] ); ?>
            </td>
            <td>
              <?= htmlspecialchars( $post['DateAjout'] ); ?>
            </td>
            <td>
                <?= htmlspecialchars( $post['Title'] ); ?>
            </td>
            <td>
              <?= htmlspecialchars( $post['FirstName'] ); ?>
              <?= htmlspecialchars( $post['LastName'] ); ?>
            </td>
            <td>
              <?= htmlspecialchars( $post['Name'] ); ?>
            </td>
            <td>
              <a
                href="admin_posts_edit.php?id=<?= intval( $post['Id'] ); ?>"
                class="btn btn-secondary"
                title="Modifier le post">
                <i class="fa fa-pen-nib" aria-hidden="true"></i>
              </a>
            </td>
            <td>
              <button 
                class="btn btn-danger btn-delete-post"  
                title="Supprimer le post"
                data-toggle="modal" 
                data-target="#delete-modal"
                data-postId='<?= intval( $post['Id'] ); ?>'>
                <i class="far fa-trash-alt" aria-hidden="true"></i>
              </button>
            </td>
          </tr>
          <?php endforeach; ?>
        </tbody>
      </table>

      <!-- Delete Modal -->
      <div class="modal fade" id="delete-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title text-danger font-weight-bold">Suppression d'un article</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <p>Voulez-vous vraiment supprimer cet article ?</p>
            </div>
            <div class="modal-footer">
         
                <button type="button" class="btn btn-secondary font-weight-bold" data-dismiss="modal">Close</button>
                <a type="button" href="admin_posts_delete.php?id=id" class="btn btn-danger font-weight-bold" id="confirm-delete">Supprimer</a>
          
            </div>
          </div>
        </div>
		  </div>			
    </section>
  </div>
</main>
