<main class="d-flex flex-column">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb m-0">
        <li class="breadcrumb-item">Administration</li>
        <li class="breadcrumb-item active" aria-current="page">Gestion des auteurs</li>
    </ol>
  </nav>
  <div class="flex-grow-1 d-md-flex align-items-stretch">
    <?php include 'admin_menu.phtml'; ?>
    <section class="col-md-8 p-5 mx-auto">
      <header class="jumbotron text-center">
          <h2 class="text-center mb-4 display-4">Gestion des auteurs</h2>
          <p class="lead">Connaître le nombre d'articles par auteur</p>
        <hr class="my-4">
      </header>
      <nav class="mb-4">
        <a class="btn bg text-white" href="admin_authors_new.php">
          <i class="fas fa-plus" aria-hidden="true"></i>
          Ajouter un auteur
        </a>
      </nav>
      <table class="table table-striped">
        <caption>Liste des auteurs</caption>
        <thead class="thead-dark">
          <tr>
            <th>ID</th>
            <th>Auteur</th>
            <th>Nombre d'articles</th>
            <th>Modifier</th>
            <th>Supprimer</th>
          </tr>
        </thead>
        <tbody>
          <?php foreach ( $authors as $author ): ?>
          <tr>
            <td><?= intval( $author['Id']) ?></td>
            <td><?= htmlspecialchars( $author['FirstName'] ) ?> <?= htmlspecialchars( $author['LastName'] ) ?></td>
            <td><?= htmlspecialchars( $author['Total'] ) ?></td>
            <td>
              <a
                href="admin_authors_edit.php?id=<?= intval( $author['Id'] ); ?>"
                class="btn btn-secondary"
                title="Modifier l'auteur">
                <i class="fa fa-pen-nib" aria-hidden="true"></i>
              </a>
            </td>
            <td>
              <?php if( $author['Total'] <= 0 ) : ?>
                <button 
                  class="btn btn-danger btn-delete-author"  
                  title="Supprimer l'auteur"
                  data-toggle="modal" 
                  data-target="#delete-modal"
                  data-authorId='<?= intval( $author['Id'] ); ?>'>
                  <i class="far fa-trash-alt" aria-hidden="true"></i>
                </button>
              <?php endif; ?>
            </td>
          </tr>
        <?php endforeach; ?>
        </tbody>
      </table>

      <!-- Modal -->
      <div class="modal fade" id="delete-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title text-danger font-weight-bold">Suppression d'un auteur</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <p>Voulez-vous vraiment supprimer cet auteur ?</p>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary font-weight-bold" data-dismiss="modal">Close</button>
              <a type="button" class="btn btn-danger font-weight-bold" href="admin_authors_delete.php?id=id" id="confirm-delete">Supprimer</a>
            </div>
          </div>
        </div>
      </div>			
      
    </section>
  </div>
</main>
