<main class="pb-5">
    <header class="jumbotron main-header">
        <h1 class="display-4 text-color">Accueil du blog</h1>
        <p class="lead text-dark">Les derniers articles postés</p>
        <hr class="my-4">
        <p class="text-dark">Récupération des 10 derniers articles du blog classés par ordre antéchronologique</p>
    </header>
    <section class="container-fluid">
        <h2 class="text-center mb-4">Les nouvelles de Tante URSULE</h2>
        <div class="d-lg-flex flex-wrap p-2">
            <?php foreach($posts as $post): ?>
                <article class="card shadow m-2 d-flex flex-column">
                    <header class="card-header bg flex-grow-1">
                        <h3 class="h4">
                        <a
                            class="text-white font-weight-bold"
                            href="show_post.php?id=<?= $post['Id'] ?>"
                            title="Consulter l'article">
                            <?= htmlspecialchars( $post['Title'] ); ?>
                        </a>
                        </h3>
                        <p class="m-0">
                            Dans la catégorie :
                            <strong class="badge badge-dark">
                            <?= htmlspecialchars( $post['Name'] ); ?>
                            </strong>
                        </p>
                    </header>
                    <div class="card-body flex-grow-0 bg-light text-dark">
                        <div class="card-text">
                        <?= htmlspecialchars( $post['SubContents'] ); ?> [...]
                        </div>
                        <p class="mt-5 card-text text-right">
                            <a
                            class="btn bg text-white"
                            href="show_post.php?id=<?= $post['Id'] ?>"
                            title="Consulter l'article">Lire la suite</a>
                        </p>
                    </div>
                    <footer class="card-footer text-white bg-secondary small">
                        Rédigé par
                        <strong>
                            <?= htmlspecialchars( $post['FirstName'] ); ?>
                            <?= htmlspecialchars( $post['LastName'] ); ?>
                        </strong>
                        le
                        <time>
                            <?= htmlspecialchars( $post['DateAjout'] ); ?>
                        </time>
                    </footer>
                    </article>
            <?php endforeach; ?>
        </div>
    </section>
</main>